version: '3.8'

services:
  app:
    build: ./app
    container_name: python_app
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: pa$$w0rd
      MYSQL_DATABASE: mydb
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: pa$$w0rd
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/db1.0.sql:/docker-entrypoint-initdb.d/db1.0.sql

volumes:
  db_data:
