-- MySQL Script generated by MySQL Workbench
-- Tue 30 Apr 2024 11:58:29 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `points` MEDIUMINT(255) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`places` (
  `place_id` INT NOT NULL AUTO_INCREMENT,
  `place_name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `points_value` TINYINT(255) UNSIGNED NOT NULL DEFAULT 255,
  `unlock_code` VARCHAR(100) NOT NULL,
  `gps_lon` FLOAT(10) NOT NULL,
  `gps_lat` FLOAT(10) NOT NULL,
  PRIMARY KEY (`place_id`),
  UNIQUE INDEX `place_id_UNIQUE` (`place_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`discoveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`discoveries` (
  `user_id` INT NOT NULL,
  `place_id` INT NOT NULL,
  `discovery_date` DATETIME NOT NULL,
  INDEX `fk_discoveries_places_idx` (`place_id` ASC) VISIBLE,
  INDEX `fk_discoveries_users_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `place_id`),
  CONSTRAINT `fk_discoveries_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discoveries_places`
    FOREIGN KEY (`place_id`)
    REFERENCES `mydb`.`places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `place_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `comment` TINYTEXT NOT NULL,
  PRIMARY KEY (`comment_id`),
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `fk_comments_places1_idx` (`place_id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_places1`
    FOREIGN KEY (`place_id`)
    REFERENCES `mydb`.`places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO places (place_name, address, unlock_code, gps_lon, gps_lat) VALUES ('PWR A1', 'wybrzeze wyspianskiego 27', 'a1-kgs823SQK', 51.10755023045328, 17.06174918205241);
INSERT INTO places (place_name, address, unlock_code, gps_lon, gps_lat) VALUES ('Habibi kebab', 'pl. grunwaldzki 4a', 'hk-hbl236POQ', 51.110324015855866, 17.055300744568495);
